project/apps/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login_page, name='login'),
    path('registration/', views.registration_page, name='registration'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/<str:pk>/', views.edit_profile, name='edit_profile'),
    path('user_profile/<str:pk>/', views.user_profile, name='user_profile'),
    path('upload_photo/', views.upload_photo, name='upload_photo'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('create_album/', views.create_album, name='create_album'),
    path('edit_album/<str:pk>/', views.edit_album, name='edit_album'),
    path('edit_photo/<str:pk>/', views.edit_photo, name='edit_photo'),
    path('edit_video/<str:pk>/', views.edit_video, name='edit_video'),
    path('delete_photo/<str:pk>/', views.delete_photo, name='delete_photo'),
    path('delete_video/<str:pk>/', views.delete_video, name='delete_video'),
    path('delete_album/<str:pk>/', views.delete_album, name='delete_album'),
    path('photos/', views.photos, name='photos'),
    path('videos/', views.videos, name='videos'),
    path('albums/', views.albums, name='albums'),
    path('photo/<str:pk>/', views.s_photo, name='photo'),
    path('video/<str:pk>/', views.s_video, name='video'),
    path('album/<str:pk>/', views.s_album, name='album'),
    path('search/', views.search, name='search'),
    path('map/<str:region>/', views.map_page, name='map'),
    path('map_ajax/', views.map_ajax, name='map_ajax'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))),
]

project/apps/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from uuid import uuid4
from io import BytesIO
from PIL import Image
from django.core.files import File


class User(AbstractUser):
    username = models.CharField(max_length=256, null=True)
    email = models.EmailField(unique=True, null=True)
    login = models.CharField(max_length=256, null=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars', default="avatar.svg")
    avatar_brightness = models.CharField(max_length=256, null=True, blank=True)
    avatar_contrast = models.CharField(max_length=256, null=True, blank=True)
    avatar_rotation = models.CharField(max_length=256, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        ordering = ['-id', '-updated']
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username or self.email


class Regions(models.Model):
    name = models.CharField(max_length=256, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id', '-updated']
        verbose_name = 'Region'
        verbose_name_plural = 'Regions'

    def __str__(self):
        return self.name


class Albums(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(null=True, upload_to='covers', default="ava1.jpg")
    brightness = models.CharField(max_length=256, null=True, blank=True)
    contrast = models.CharField(max_length=256, null=True, blank=True)
    rotation = models.CharField(max_length=256, null=True, blank=True)
    title = models.CharField(max_length=256, null=True)
    description = models.TextField(null=True, blank=True)
    tags = models.CharField(max_length=256, null=True, blank=True)
    status = models.BooleanField(default=False)
    coauthors = models.ManyToManyField(User, related_name='coauthors', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id', '-updated']
        verbose_name = 'Album'
        verbose_name_plural = 'Albums'

    def __str__(self):
        return self.title


def get_photo_upload_path(instance, filename):
    unique_filename = str(uuid4())  # Генерируем случайное уникальное значение
    return f"photos/{unique_filename}_{filename}"  # Путь для сохранения файла с использованием уникального значения


def get_photo_reducted_upload_path(instance, filename):
    unique_filename = str(uuid4())  # Генерируем случайное уникальное значение
    return f"photos/reducted/{unique_filename}_{filename}"


def compress(image):
    im = Image.open(image)
    im = im.convert("RGB")  # Преобразование изображения в режим RGB
    im_io = BytesIO()
    im.save(im_io, format='JPEG', quality=70)
    resized_image = InMemoryUploadedFile(
        im_io,
        None,
        f"{image.name.split('.')[0]}.jpg",  # Сохраняем в формате JPEG
        'image/jpeg',
        im_io.tell(),
        None
    )
    return resized_image


class UploadedPhotos(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(null=True, upload_to=get_photo_upload_path, default="ava1.jpg")
    reducted = models.ImageField(null=True, upload_to=get_photo_reducted_upload_path, default="ava1.jpg")
    description = models.TextField(null=True, blank=True)
    tags = models.CharField(max_length=256, null=True, blank=True)
    album = models.ForeignKey(Albums, on_delete=models.SET_NULL, null=True, blank=True)
    region = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True, blank=True)
    brightness = models.CharField(max_length=256, null=True, blank=True)
    contrast = models.CharField(max_length=256, null=True, blank=True)
    rotation = models.CharField(max_length=256, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id', '-updated']
        verbose_name = 'Uploaded Photo'
        verbose_name_plural = 'Uploaded Photos'

    def save(self, *args, **kwargs):
        # call the compress function
        new_image = compress(self.photo)
        # set self.image to new_image
        self.reducted = new_image
        # save
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.photo)


def get_video_upload_path(instance, filename):
    unique_filename = str(uuid4())  # Генерируем случайное уникальное значение
    return f"videos/{unique_filename}_{filename}"  # Путь для сохранения файла с использованием уникального значения


class UploadedVideos(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    video = models.FileField(null=True, upload_to=get_video_upload_path, default="ava1.jpg")
    cover = models.ImageField(null=True, upload_to='videos/covers', default="favicon.png")
    description = models.TextField(null=True, blank=True)
    tags = models.CharField(max_length=256, null=True, blank=True)
    album = models.ForeignKey(Albums, on_delete=models.SET_NULL, null=True, blank=True)
    region = models.ForeignKey(Regions, on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id', '-updated']
        verbose_name = 'Uploaded Video'
        verbose_name_plural = 'Uploaded Videos'

    def __str__(self):
        return str(self.video)

project/apps/base/views.py
from django.shortcuts import render, redirect
from . import models
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from . import forms
from .coreutils import detect_objects
import re
import json
from django.http import JsonResponse


def main(request):
    photo = models.UploadedPhotos.objects.all()
    video = models.UploadedVideos.objects.all()

    context = {'photos': photo, 'videos': video}
    return render(request, 'base/main.htm', context)


def login_page(request):
    if request.user.is_authenticated:
        return redirect('main')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        # noinspection PyBroadException
        try:
            models.User.objects.get(email=email)
        except BaseException:
            messages.error(request, "Пароль или Почта неправльная")

        user = authenticate(request, email=email, password=password)

        # noinspection PyBroadException
        try:
            login(request, user)
            return redirect('main')
        except BaseException:
            messages.error(request, "Просто неправильный ответ...")  # Don't touch it

    return render(request, 'base/login.htm')


def registration_page(request):
    if request.user.is_authenticated:
        return redirect('main')

    form = forms.UnterUserCreationForm

    if request.method == 'POST':
        form = forms.UnterUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            form.save()
            login(request, user)
            return redirect('main')
        else:
            messages.error(request, 'Возникла ошибка в процессе регистрации')
            messages.error(request, 'Либо пароль слишком слабый')

    context = {'form': form}
    return render(request, 'base/registration.htm', context)


@login_required(login_url='main')
def logout_page(request):
    logout(request)
    return redirect('main')


@login_required(login_url='login')
def profile(request):
    # noinspection PyBroadException
    try:
        user_photos = models.UploadedPhotos.objects.filter(owner=request.user)
        user_videos = models.UploadedVideos.objects.filter(owner=request.user)
        user_albums = models.Albums.objects.filter(owner=request.user)
    except BaseException:
        user_photos = ''
        user_videos = ''
        user_albums = ''

    context = {
        'user_photos': user_photos,
        'user_videos': user_videos,
        'user_albums': user_albums
    }

    return render(request, 'base/profile.htm', context)


def user_profile(request, pk):
    user = models.User.objects.get(id=pk)

    if request.user.id == user.id:
        return redirect('profile')

    # noinspection PyBroadException
    try:
        user_photos = models.UploadedPhotos.objects.filter(owner=user.id)
        user_videos = models.UploadedVideos.objects.filter(owner=user.id)
        user_albums = models.Albums.objects.filter(owner=user.id)
    except BaseException:
        user_photos = ''
        user_videos = ''
        user_albums = ''

    context = {
        'user_photos': user_photos,
        'user_videos': user_videos,
        'user_albums': user_albums,
        'user': user,
    }
    return render(request, 'base/profile.htm', context)


@login_required(login_url='login')
def edit_profile(request, pk):
    user = models.User.objects.get(id=pk)
    form = forms.UserEditForm(request.POST or None, request.FILES or None, instance=user)

    if request.method == 'POST':
        if form.is_valid():
            form.avatar_brightness = request.POST.get('brightness')
            form.avatar_contrast = request.POST.get('contrast')
            form.avatar_rotation = request.POST.get('rotation')
            form.save()
            return redirect('user_profile', pk=user.id)

    context = {'user': user, 'form': form}
    return render(request, 'base/components/edit_profile.htm', context)


@login_required(login_url='login')
def upload_photo(request):
    form = forms.PhotoForm

    if request.method == 'POST':
        form = forms.PhotoForm(request.POST or None, request.FILES or None)
        # path_pattern = 'project/static/uploads/photos/0baf04d9-65c6-45fa-af4d-a21f4e4943a8_ww.jpg'

        if form.is_valid():
            photo = form.save(commit=False)
            photo.owner = request.user
            photo.brightness = request.POST.get('brightness')
            photo.contrast = request.POST.get('contrast')
            photo.rotation = request.POST.get('rotation')
            form.save()
            photo.tags = detect_objects(f"project/static{str(photo.photo.url)}")
            form.save()

        return redirect('photos')

    context = {'form': form}
    return render(request, 'base/components/upload_photo.htm', context)


@login_required(login_url='login')
def upload_video(request):
    form = forms.VideoForm

    if request.method == 'POST':
        form = forms.VideoForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            video = form.save(commit=False)
            video.owner = request.user
            form.save()
            video.tags = detect_objects(f"project/static{str(video.cover.url)}")
            form.save()

        return redirect('videos')

    context = {'form': form}
    return render(request, 'base/components/upload_video.htm', context)


@login_required(login_url='login')
def create_album(request):
    form = forms.AlbumForm

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            album = form.save(commit=False)
            album.owner = request.user
            album.brightness = request.POST.get('brightness')
            album.contrast = request.POST.get('contrast')
            album.rotation = request.POST.get('rotation')
            form.save()
            album.tags = detect_objects(f"project/static{str(album.photo.url)}")
            form.save()
            form.save_m2m()

        return redirect('albums')

    context = {'form': form}
    return render(request, 'base/components/create_album.htm', context)


def s_photo(request, pk):
    single_photo = models.UploadedPhotos.objects.get(id=pk)

    context = {'photo': single_photo}
    return render(request, 'base/single_photo.htm', context)


def s_video(request, pk):
    single_video = models.UploadedVideos.objects.get(id=pk)

    context = {'video': single_video}
    return render(request, 'base/single_video.htm', context)


def s_album(request, pk):
    single_album = models.Albums.objects.get(id=pk)

    if not single_album.status and request.user != single_album.owner:
        return redirect('main')

    context = {'album': single_album}
    return render(request, 'base/single_album.htm', context)


def photos(request):
    photo = models.UploadedPhotos.objects.all()

    context = {'photos': photo}
    return render(request, 'base/photos.htm', context)


def videos(request):
    video = models.UploadedVideos.objects.all()

    context = {'videos': video}
    return render(request, 'base/videos.htm', context)


def albums(request):
    album = models.Albums.objects.all()

    context = {'albums': album}
    return render(request, 'base/albums.htm', context)


@login_required(login_url='login')
def edit_photo(request, pk):
    photo = models.UploadedPhotos.objects.get(id=pk)
    form = forms.PhotoForm(request.POST or None, request.FILES or None, instance=photo)

    if request.method == 'POST':
        if form.is_valid():
            x_photo = form.save(commit=False)
            x_photo.brightness = request.POST.get('brightness')
            x_photo.contrast = request.POST.get('contrast')
            x_photo.rotation = request.POST.get('rotation')
            form.save()
            return redirect('photo', pk=photo.id)

    context = {'photo': photo, 'form': form}
    return render(request, 'base/components/edit_photo.htm', context)


@login_required(login_url='login')
def edit_video(request, pk):
    video = models.UploadedVideos.objects.get(id=pk)
    form = forms.VideoForm(request.POST or None, request.FILES or None, instance=video)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('videos')

    context = {'video': video, 'form': form}
    return render(request, 'base/components/edit_video.htm', context)


@login_required(login_url='login')
def edit_album(request, pk):
    album = models.Albums.objects.get(id=pk)
    form = forms.AlbumForm(request.POST or None, request.FILES or None, instance=album)

    if request.method == 'POST':
        if form.is_valid():
            x_album = form.save(commit=False)
            x_album.brightness = request.POST.get('brightness')
            x_album.contrast = request.POST.get('contrast')
            x_album.rotation = request.POST.get('rotation')
            form.save()
            return redirect('album', pk=album.id)

    context = {'album': album, 'form': form}
    return render(request, 'base/components/edit_album.htm', context)


@login_required(login_url='login')
def delete_photo(request, pk):
    if request.user != models.UploadedPhotos.objects.get(id=pk).owner:
        return redirect('main')
    else:
        models.UploadedPhotos.objects.get(id=pk).delete()
        return redirect('profile')


@login_required(login_url='login')
def delete_video(request, pk):
    if request.user != models.UploadedVideos.objects.get(id=pk).owner:
        return redirect('main')
    else:
        models.UploadedVideos.objects.get(id=pk).delete()
        return redirect('profile')


@login_required(login_url='login')
def delete_album(request, pk):

project/apps/base/templates/base/albums.htm
{% extends 'index.htm' %}
{% load static %}
{% block title %} DOLOR | Альбомы {% endblock %}
{% block content %}
    <div class="content padding_content">
        <div class="container">
            <a href="{{ request.META.HTTP_REFERER }}" class="arrow_back">
                <img src="{% static 'assets/img/arrow_back.png' %}">
            </a>
            {% for album in albums %}
                {% if album.status %}
                    <div class="row all_media_full">
                        <div class="col carousel photo_view_full">
                            <img src="{{ album.photo.url }}" class="pic photo_view_full_img" alt="" style="transform: scale(1) rotate({{ album.rotation }}deg); filter: brightness({{ album.brightness }}) contrast({{ album.contrast }});">
                            {% for photo in album.uploadedphotos_set.all %}
                                <img src="{{ photo.reducted.url }}" class="pic photo_view_full_img" alt="" style="transform: scale(1) rotate({{ photo.rotation }}deg); filter: brightness({{ photo.brightness }}) contrast({{ photo.contrast }});">
                            {% endfor %}
                            {% for video in album.uploadedvideos_set.all %}
                                <video class="pic photo_view_full_img" autoplay muted loop src="{{ video.video.url}}"></video>
                            {% endfor %}
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev" id="back">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next" id="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                        <div class="col photo_view_information">
                            <div class="published_img_info">
                                <div class="view_photo_user_img user_photo_box">
                                    <img src="{{ album.owner.avatar.url }}" class="user_photo_img">
                                </div>
                                <div class="user_name view_user_name">
                                    <a href="{% url 'user_profile' album.owner.id %}" class="heading_txt">@{{ album.owner }}</a>
                                    <a href="{{ album.photo.url }}" class="download_btn" download><img alt="" src="{% static 'assets/img/download.png' %}"></a>
                                </div>
                            </div>
                            <div class="view_album_name heading_txt my-2">
                                {{ album.title }}
                                <!-- если пользователь является создателем альбома (то ему доступна кнопка редактирования)-->
                                {% if request.user == album.owner %}
                                    <a href="{% url 'edit_album' album.id %}"><img src="{% static 'assets/img/edit.svg' %}" class="edit_btn"></a>
                                {% endif %}
                            </div>
                            <div class="view_media_description">{{ album.description }}</div>
                            <div class="view_media_description">Соавторы: {% for coauthors in album.coauthors.all %} | <a href="{% url 'user_profile' coauthors.id %}">{{ coauthors.username }}</a> | {% endfor %}</div>
                            <div class="view_photo_hashtag_str grey_txt">
                                <p>{{ album.tags }}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <script defer type="text/javascript" rel="script" src="{% static 'assets/js/script_all_albums_slider.js' %}"></script>
{% endblock %}

project/apps/base/templates/base/login.htm
{% extends 'index.htm' %}
{% load static %}
{% block title %} DOLOR | Авторизация {% endblock %}
{% block content %}
    <div class="content">
        <div class="container">
            <div class="login_background_block">
                <div class="inner_login_background_block">
                    {% if messages %}
                        {% for message in messages %}
                            <p class="heading_txt">{{ message }}</p>
                        {% endfor %}
                    {% else %}
                        <p class="heading_txt">Привет! Кто здесь?</p>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <p class="label">Эл. Почта</p>
                        <input type="text" placeholder="Эл. Почта" name="email" id="login"  title="Введите вашу почту" class="area" required>
                        <p class="form_p" id="login_p"><!--Введите корректный логин--></p>
                        <p class="label">Пароль:</p>
                        <input type="password" placeholder="Пароль" name="password" id="password" title="Введите ваш пароль" class="area" required>
                        <p class="form_p" id="password_p"><!--Слишком короткий пароль--></p>
                        <input type="submit" value="Войти" id="btn" class="btn">
                        <p class="link">Нет аккаунта? <a href="{% url 'registration' %}"><span>Зарегистрируйся</span></a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/apps/base/templates/base/main.htm
{% extends 'index.htm' %}
{% load static %}
{% block title %} DOLOR | Main {% endblock%}
{% block content %}
    <div class="content">
        <div class="container">
            <div class="row g-3">
                {% for photo in photos %}
                    {% if photo.album.status or photo %}
                        <a href ="{% url 'photo' photo.id %}" class="col-xl-2 col-md-3 col-sm-12">
                            <div class="crop_box_img">
                                <img class="published_img card-img-top" src="{{ photo.reducted.url }}" alt="Card image cap" style="transform: scale(1) rotate({{ photo.rotation }}deg); filter: brightness({{ photo.brightness }}) contrast({{ photo.contrast }});">
                            </div>
                            <div class="published_img_info">
                                <div class="user_photo_box">
                                    <img src="{{ photo.owner.avatar.url }}" class="user_photo_img">
                                </div>
                                <div class="user_name">
                                    <p>@{{ photo.owner }}</p>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="row g-3">
                {% for video in videos %}
                    {% if video.album.status or video %}
                        <a href ="{% url 'video' video.id %}" class="col-xl-2 col-md-3 col-sm-12">
                            <div class="crop_box_img">
                                <img class="published_video published_album_img card-img-top" src="{{ video.cover.url }}">
                                <img class="play_btn " src="{% static 'assets/img/playbtn1.png' %}">
                            </div>
                            <div class="published_img_info">
                                <div class="user_photo_box">
                                    <img src="{{ video.owner.avatar.url }}" class="user_photo_img">
                                </div>
                                <div class="user_name">
                                    <p>@{{ video.owner }}</p>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

project/apps/base/templates/base/registration.htm
{% extends 'index.htm' %}
{% load static %}
{% block title %} DOLOR | Регистрация {% endblock %}
{% block content %}
    <div class="content">
        <div class="container">
            <div class="reg_background_block">
                {% if messages %}
                    {% for message in messages %}
                        <p class="heading_txt">{{ message }}</p>
                    {% endfor %}
                {% else %}
                    <p class="heading_txt">Впервые? Тебе здесь понравится</p>
                {% endif %}
                <form method="post" id="reg_form">
                    {% csrf_token %}
                    <p class="label">Имя:</p>
                    {{ form.username }}
                    <p class="form_p" id="login_p"><!--Введите корректный логин--></p>
                    <p class="label">Email:</p>
                    {{ form.email }}
                    <p class="form_p" id="name_p"><!--Введите корректное имя--></p>
                    <p class="label">Логин:</p>
                    {{ form.login }}
                    <p class="form_p" id="email_p"><!--Введите корректную почту--></p>
                    <p class="label">Пароль:</p>
                    {{ form.password1 }}
                    <p class="form_p" id="password_p"><!--Слишком короткий пароль--></p>
                    <p class="label">Пароль еще раз:</p>
                    {{ form.password2 }}
                    <p class="form_p" id="password_repeat_p"><!--Пароли не совпадают--></p>
                    <p><input type="checkbox" id="rules" class="area" required>Согласие с правилами регистрации</p>
                    <input type="submit" value="Зарегистрироваться" id="btn" class="btn">
                    <p class="link">Уже есть аккаунт? <a href="{% url 'login' %}"><span>Войди</span></a></p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

project/apps/base/templates/base/single_album.htm
{% extends 'index.htm' %}
{% load static %}
{% block title %} DOLOR | Альбомы {% endblock %}
{% block content %}
    <div class="content padding_content">
        <div class="container">
            <a href="{{ request.META.HTTP_REFERER }}" class="arrow_back">
                <img src="{% static 'assets/img/arrow_back.png' %}">
            </a>
            <div class="row">
                <div class="col carousel photo_view_full">
                    <img src="{{ album.photo.url }}" class="pic photo_view_full_img" alt="" style="transform: scale(1) rotate({{ album.rotation }}deg); filter: brightness({{ album.brightness }}) contrast({{ album.contrast }});">
                    {% for photo in album.uploadedphotos_set.all %}
                        <img src="{{ photo.reducted.url }}" class="pic photo_view_full_img" alt="" style="transform: scale(1) rotate({{ photo.rotation }}deg); filter: brightness({{ photo.brightness }}) contrast({{ photo.contrast }});">
                    {% endfor %}
                    {% for video in album.uploadedvideos_set.all %}
                        <video class="pic photo_view_full_img" autoplay muted loop src="{{ video.video.url}}"></video>
                    {% endfor %}
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev" id="back">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next" id="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
                <div class="col photo_view_information">
                    <div class="published_img_info">
                        <div class="view_photo_user_img user_photo_box">
                            <img src="{{ album.owner.avatar.url }}" class="user_photo_img">
                        </div>
                        <div class="user_name view_user_name">
                            <a href="{% url 'user_profile' album.owner.id %}" class="heading_txt">@{{ album.owner }}</a>
                            <a href="{{ album.photo.url }}" class="download_btn" download><img src="{% static 'assets/img/download.png' %}"></a>
                        </div>
                    </div>
                    <div class="view_album_name heading_txt my-2">
                        {{ album.title }}
                        <!-- если пользователь является создателем альбома (то ему доступна кнопка редактирования)-->
                        {% if request.user == album.owner %}
                            <a href="{% url 'edit_album' album.id %}"><img alt="" src="{% static 'assets/img/edit.svg' %}" class="edit_btn"></a>
                        {% endif %}
                    </div>
                    <div class="view_media_description">{{ album.description }}</div>
                    <div class="view_media_description">Соавторы: {% for coauthors in album.coauthors.all %} |{{ coauthors.username }}| {% endfor %}</div>
                    <div class="view_photo_hashtag_str grey_txt">
                        <p>{{ album.tags }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script defer type="text/javascript" rel="script" src="{% static 'assets/js/script_slider.js' %}"></script>
{% endblock %}